### PR TITLE
#464: Improve efficiency of cluster swap stage of clustering transfer strategy

### LINKED ISSUE #446: Improve efficiency of clustering transfer strategy
This is related to a discussion with @nlslatt

### LINKED ISSUE #464: Improve execution speed of cluster swap stage in clustering algorithm
**Motivation:** the initial implementation computes explicitly several quantities (e.g. clusters themselves) after each swap.
Instead, updates should be done.

Furthermore better instrumentation & statistics are needed to track load-balancing performance.

This is a sub-issue of the broader #446

### PR DESCRIPTION
**Pull request by ppebay**
Resolves #464  

Related to #446

### CODE REVIEW

**Comment by ppebay** [comment]
@nlslatt if you get a chance (and time), this branch contains performance improvements to the **swapping stage** of the clustering transfer strategy. I added some stats (and fixed some that turned out to be incorrect regarding rejection rates), so any feedback as to whether execution speed is improved with your data sets would be appreciated.

Meanwhile I am continuing to work on the **sub-clustering stage**. Thanks

**Comment by ppebay** [comment]
As discussed with @nlslatt and @lifflander this is ready to be reviewed

**Comment by nlslatt** [comment]
@PPP You should open an issue that motivates your changes and link it to that issue instead of the one that you don't want closed.

**Comment by nlslatt** [comment]
@ppebay It also looks like you have commits from other PRs on this branch. Please rebase and make sure the branch is clean.

**Comment by ppebay** [comment]
Thanks @nlslatt this is now fixing #464 

Regarding the commits from other branches, this is because this branch was rebased on develop twice in order to incorporate other changes along the way.

**Comment by ppebay** [comment]
This is now superseded by new PR #465

**Pull request closed without merging**
