### PR TITLE
#468: update master from develop v1.0.1

### LINKED ISSUE #457: Create 1.0.1 micro revision
This is a follow-on to #440, which will integrate in particular  PR #454  (fixing #453 )

### LINKED ISSUE #468: Update master from develop v1.0.1
Update master ahead of the release of v1.0.1

### PR DESCRIPTION
**Pull request by cwschilly**
Fixes #468

### CODE REVIEW

**Review by ppebay — APPROVED** [review]
+1

**Review by nlslatt — COMMENTED** [review]
It looks like someone has probably been merging PRs that do not pass all checks, because I see stuff on develop now causing the checks for this PR to fail. Choices like this could complicate all our processes down the road (this accidentally happened in the vt repo and has been a nightmare ever since).

This PR should not "fix" the a closed issue. A new issue should be created.

**Comment by cwschilly** [comment]
@nlslatt @ppebay Should I create an issue for the dependabot PR to fix (in hindsight) and then rebase/rename the commit?

**Comment by nlslatt** [comment]
> @nlslatt @ppebay Should I create an issue for the dependabot PR to fix (in hindsight) and then rebase/rename the commit?
> 
> The other failing pipeline is because the branch of this PR is `develop`

@lifflander?

**Comment by lifflander** [comment]
> > @nlslatt @ppebay Should I create an issue for the dependabot PR to fix (in hindsight) and then rebase/rename the commit?
> > The other failing pipeline is because the branch of this PR is `develop`
> 
> @lifflander?

I think it's worth doing that although it will break everyone's develop if we force push to it.

**Comment by nlslatt** [comment]
I was going to ask if we updated the version number in the `VERSION` file mentioned in the `LICENSE` file, but it seems we don't have one yet. We should probably create one before merging into master.

**Comment by cwschilly** [comment]
> I was going to ask if we updated the version number in the `VERSION` file mentioned in the `LICENSE` file, but it seems we don't have one yet. We should probably create one before merging into master.

I have created a VERSION file in PR #473

**Review by ppebay — APPROVED** [review]
THanks for additional change

**Comment by cwschilly** [comment]
@ppebay @nlslatt @lifflander We've now merged all relevant PRs to v1.0.1 -- once we merge this PR I can go ahead with the release

**Review by nlslatt — APPROVED** [review]

**Comment by ppebay** [comment]
I think only either @lifflander or @nlslatt can merge this PR

**Review by nlslatt — APPROVED** [review]

**Pull request merged**
