### PR TITLE
#376: rework import structure in lbafapp and other files

### LINKED ISSUE #376: Rework import structure in LBAF_app and other files
1. Reorganize Import statements and PYTHONPATH

In many files some module import are done by code using the `sys.path.append` functions but it will be cleaner if we use the PYTHONPATH environment variable like this:

`export PYTHONPATH="${PYTHONPATH}:/path/to/project"`

Currently many files contains a code like the following and with the environment variable it won't be needed

https://github.com/DARMA-tasking/LB-analysis-framework/blob/3720ef281e698b31e3bee339b2e94ad83cd59a34/src/lbaf/Applications/LBAF_app.py#L11-L16

After that import statements will be correctly grouped at the top of python modules it will be cleaner and more compliant with pylint 

2. Rework setup configuration to make setup work for Python 3.9 (currently setup requires Python 3.8)

### PR DESCRIPTION
**Pull request by tlamonthezie**
Fixes #376 

This pull request includes the following related to the rework of the import structure

- Setup lbaf in editable mode (added to the requirements files for pip)
- Make setup working and test :
      - Validation & Corrections for the package setup
      - Addition of a console script (to run the LBAF application directly by typing `lbaf` in a console)
- Some code quality changes (with the help of Pylint)
- Some development configuration files to help with code quality
- Refactoring
- upgrade acceptance tests and stepper tests to be run also with python 3.9 on the CI
- Update README.md

Also includes changes from #367 following a merge done because of too many conflicts between the 2 branches

### CODE REVIEW

**Comment by ppebay** [comment]
Please rebase with #374

**Comment by ppebay** [comment]
@tlamonthezie Not sure why but there are still many conflicts even after the rebase

**Comment by tlamonthezie** [comment]
> @tlamonthezie Not sure why but there are still many conflicts even after the rebase

Yes i see. I dont know why... i will merge develop into the 376 branch again to resolve that asap

**Comment by ppebay** [comment]
@tlamonthezie I have the following problem:
```
[pppebay@localhost]~/Documents/Git/LB-analysis-framework/src/lbaf/Applications$ python LBAF_app.py --config conf.yaml
Traceback (most recent call last):
  File "LBAF_app.py", line 11, in <module>
    from lbaf import __version__, PROJECT_PATH
ModuleNotFoundError: No module named 'lbaf'
```
when trying to run the command: `python LBAF_app.py --config conf.yaml`

**Pull request closed without merging**
