### PR TITLE
#289: Ensure that JSON trace files are read only once when multiple phases are sought

### LINKED ISSUE #289: Ensure that JSON trace files are read only once when multiple phases are sought
Step to illustrate the problem to be solved: run the following
```
python LBAF_app.py --conf every20phases.yaml
```
in `lbaf/Applications`.

### PR DESCRIPTION
**Pull request by marcinwrobel1986**
### THIS PR:
- files are read once
- files are read with full use of processor (multiprocessing)
- tests and imports are fixed due to the changes

closes #289

### CODE REVIEW

**Comment by marcinwrobel1986** [comment]
@ppebay this is good to be checked. I am working now on issue #290 making other improvements to speed up things a bit or probably in some cases a lot. I will be based on 289 branch, so please let me know once it is merged. Thanks!

**Comment by ppebay** [comment]
Thanks @marcinwrobel1986 will review today

**Comment by ppebay** [comment]
Adding @nmm0 as reviewer, because we used the branch for the live session

**Review by ppebay — COMMENTED** [review]
Looking good for me, but will let @nmm0 giving final approval as he tested it with his own dataset

**Review by nmm0 — APPROVED** [review]
Looks good to me, it dramatically improved loading performance on a larger dataset for me

**Pull request merged**
