### PR TITLE
#269: added printing and calculating statistics from sub-phases

### LINKED ISSUE #269: Report subphase-sensitive imbalance alongside general imbalance
See https://github.com/DARMA-tasking/vt/issues/1616 for the relevant math

### PR DESCRIPTION
**Pull request by marcinwrobel1986**
- added get_load from sub-phases in Rank
- added compute_subphases to work models
- added printing statistics from sub-phases in algorithms and main LBAF routine
- added get_subphases_time to object
- added printing statistics from sub-phases when populating from log
- fixed returned type for is_sentinel in Rank

closes #269

### CODE REVIEW

**Comment by marcinwrobel1986** [comment]
@ppebay Philippe please take a look if what I have done make sense. Best would be to try with `nolb-8color-16nodes-data` dataset. Thanks!

**Comment by PhilMiller** [comment]
It looks like there was a small mis-communication of what we were looking for. We primarily want the statistics computed and reported for each subphase, not sums over all of them.

Once we have that, then we can start doing comparisons between what an aggregate of the subphases shows and what's seen for the entire phase.

**Comment by ppebay** [comment]
@marcinwrobel1986 are we ready to review this PR?

**Comment by marcinwrobel1986** [comment]
We will be tomorrow.

**Comment by ppebay** [comment]
@marcinwrobel1986 is this PR ready for review?

**Comment by marcinwrobel1986** [comment]
> @marcinwrobel1986 is this PR ready for review?

@ppebay this is calculating the load from subphases, but **all** the subphases. This part is finished and ready for review and to be merged. In current situation it would be a good idea to merge that and create another issue, with proper description that Phil created, where one would implement statistics computed and reported for each subphase. Below is Phil's comment:

> It looks like there was a small mis-communication of what we were looking for. We primarily want the statistics computed and reported for each subphase, not sums over all of them. Once we have that, then we can start doing comparisons between what an aggregate of the subphases shows and what's seen for the entire phase.

**Comment by PhilMiller** [comment]
Computing a summed load across all of the subphases is not especially useful functionality. The point is to do the subphase-sensitive calculations that would let us apply reasoning as described in this report: https://github.com/DARMA-tasking/vector-balancing-report

**Comment by ppebay** [comment]
@PhilMiller I agree. 

Should we nevertheless merge this current PR -- or discard it altogether, as the summation across all subphases is not useful?

**Comment by PhilMiller** [comment]
Discard it, or fix it to do the useful things.

**Comment by ppebay** [comment]
Discarding this PR that is not doing what is needed

**Pull request closed without merging**
