### PR TITLE
#256: test phase stepper with real data and once case to CI

### LINKED ISSUE #256: Create reference/test cases for the phase stepper algorithm
This is to ensure that this algorithm does work as expected with data that has actually multiple phases

### PR DESCRIPTION
**Pull request by ppebay**
Fixes #256

### CODE REVIEW

**Comment by ppebay** [comment]
@marcinwrobel1986 do you have a suggestion as to how we could use the configuration filed called `step.yaml` that is currently in the `Applications` directory of this branch, and instead of keeping it there, make it a CI acceptance test.

We could for instance verify that it does indeed run through 8 phases, and the imbalance at the end is equal to the one at the start. 

Thanks

**Comment by ppebay** [comment]
This MR is now ready to be finalized @marcinwrobel1986 , with the `step.yaml` configuration file being removed from `Applications` and inserted into the CI. I have added the corresponding data in:
```
data/nolb-8color-16nodes-11firstphases/
```
where the first 11 phases (i.e., with IDs from 0 to 10) have been extracted from the original dataset.

Regarding what needs to be check, I think the easiest thing to validate is to make sure that the imbalance of **rank works** (watch out in the output, there are also results for the loads and volumes) are output as follows:
```
[lbsStatistics] 	cardinality: 32  sum: 10.5817  imbalance: 0.992173
[lbsStatistics] 	cardinality: 32  sum: 0.642948  imbalance: 4.91849
[lbsStatistics] 	cardinality: 32  sum: 0.526383  imbalance: 0.221116
[lbsStatistics] 	cardinality: 32  sum: 0.521197  imbalance: 0.0442304
[lbsStatistics] 	cardinality: 32  sum: 0.52225  imbalance: 0.0461051
[lbsStatistics] 	cardinality: 32  sum: 0.520378  imbalance: 0.0469951
[lbsStatistics] 	cardinality: 32  sum: 0.520078  imbalance: 0.0430356
[lbsStatistics] 	cardinality: 32  sum: 0.520286  imbalance: 0.0532831
[lbsStatistics] 	cardinality: 32  sum: 0.520617  imbalance: 0.0466161
[lbsStatistics] 	cardinality: 32  sum: 0.547612  imbalance: 1.44446
[lbsStatistics] 	cardinality: 32  sum: 0.522944  imbalance: 0.098434
```
(11 iterations of the stepper).

After that we should be able to merge. Thanks!

**Comment by marcinwrobel1986** [comment]
> This MR is now ready to be finalized @marcinwrobel1986 , with the `step.yaml` configuration file being removed from `Applications` and inserted into the CI. I have added the corresponding data in:
> 
> ```
> data/nolb-8color-16nodes-11firstphases/
> ```
> 
> where the first 11 phases (i.e., with IDs from 0 to 10) have been extracted from the original dataset.
> 
> Regarding what needs to be check, I think the easiest thing to validate is to make sure that the imbalance of **rank works** (watch out in the output, there are also results for the loads and volumes) are output as follows:
> 
> ```
> [lbsStatistics] 	cardinality: 32  sum: 10.5817  imbalance: 0.992173
> [lbsStatistics] 	cardinality: 32  sum: 0.642948  imbalance: 4.91849
> [lbsStatistics] 	cardinality: 32  sum: 0.526383  imbalance: 0.221116
> [lbsStatistics] 	cardinality: 32  sum: 0.521197  imbalance: 0.0442304
> [lbsStatistics] 	cardinality: 32  sum: 0.52225  imbalance: 0.0461051
> [lbsStatistics] 	cardinality: 32  sum: 0.520378  imbalance: 0.0469951
> [lbsStatistics] 	cardinality: 32  sum: 0.520078  imbalance: 0.0430356
> [lbsStatistics] 	cardinality: 32  sum: 0.520286  imbalance: 0.0532831
> [lbsStatistics] 	cardinality: 32  sum: 0.520617  imbalance: 0.0466161
> [lbsStatistics] 	cardinality: 32  sum: 0.547612  imbalance: 1.44446
> [lbsStatistics] 	cardinality: 32  sum: 0.522944  imbalance: 0.098434
> ```
> 
> (11 iterations of the stepper).
> 
> After that we should be able to merge. Thanks!

@ppebay Have you run it like at least 3 times and compare the results?

**Comment by marcinwrobel1986** [comment]
@ppebay Philippe I just ran LBAF with your `step.yaml` and when it gets on each time-step:
```Bash
[lbsPhase] Read 480 objects from time-step 0 of data files with prefix <project_path>/LB-analysis-framework/data/nolb-8color-16nodes-11firstphases/stats
```
It is reading ALL THE FILES and validating them. 

BTW I think the name of the data files should be changed from `stats` to `data`, as these files are type of `LBDatafile`

**Review by marcinwrobel1986 — APPROVED** [review]
ok, I think we can merge that

**Pull request merged**
