### PR TITLE
#376: rework import structure in lbafapp and other files

### LINKED ISSUE #376: Rework import structure in LBAF_app and other files
1. Reorganize Import statements and PYTHONPATH

In many files some module import are done by code using the `sys.path.append` functions but it will be cleaner if we use the PYTHONPATH environment variable like this:

`export PYTHONPATH="${PYTHONPATH}:/path/to/project"`

Currently many files contains a code like the following and with the environment variable it won't be needed

https://github.com/DARMA-tasking/LB-analysis-framework/blob/3720ef281e698b31e3bee339b2e94ad83cd59a34/src/lbaf/Applications/LBAF_app.py#L11-L16

After that import statements will be correctly grouped at the top of python modules it will be cleaner and more compliant with pylint 

2. Rework setup configuration to make setup work for Python 3.9 (currently setup requires Python 3.8)

### PR DESCRIPTION
**Pull request by tlamonthezie**
Fixes #376 

This pull request includes the following related to the rework of the import structure

- Setup lbaf in editable mode (added to the requirements files for pip)
- Make setup working and test :
      - Validation & Corrections for the package setup
      - Addition of a console script (to run the LBAF application directly by typing `lbaf` in a console)
- Some code quality changes (with the help of Pylint)
- Some development configuration files to help with code quality
- Refactoring
- upgrade acceptance tests and stepper tests to be run also with python 3.9 on the CI
- Update README.md

Also includes changes from #367 following a merge done because of too many conflicts between the 2 branches

### CODE REVIEW

**Comment by ppebay** [comment]
@tlamonthezie when trying to run `python LBAF_app.py --config conf.yaml` for this branch, I am getting the following error:

```
Traceback (most recent call last):
  File "LBAF_app.py", line 11, in <module>
    from lbaf import __version__, PROJECT_PATH
ModuleNotFoundError: No module named 'lbaf'
```

**Comment by tlamonthezie** [comment]
> 

Hello @ppebay it seems that your python path is not corrent or you did not install the updated requirements file 
To install the requirements in dev mode run `pip install -r requirements-{python-version}.txt`
As an alternative you can fix the python path by running `export PYTHONPATH=${PYTHONPATH}:{YOUR_PROJECT_PATH}/src` to enable python to resolve `lbaf...` imports

**Comment by ppebay** [comment]
@tlamonthezie I am not sure what you mean by the fact that my Python path not being valid, as I have not changed anything, and am able to run LBAF `develop` without any issue. It is only with this PR that I am encountering the problem described above.

**Comment by tlamonthezie** [comment]
> @tlamonthezie I am not sure what you mean by the fact that my Python path not being valid, as I have not changed anything, and am able to run LBAF `develop` without any issue. It is only with this PR that I am encountering the problem described above.

Please run again the comand to install the requirements and and let me know if it works. In the CI and on my machie it works correctlly. The way we run LBAF with `develop` is no more applicable with this PR because the full logic of imports has been changed

**Comment by ppebay** [comment]
@tlamonthezie now I understand! 
I thought my packages were up-to-date (for 3.8) but with the latest changes it's not the case any more. Now that makes more sense like this. Thank you.

I was able to run, and I am now verifying, test case by test case.

Stay tuned...

**Comment by ppebay** [comment]
Everything working as expected.

Thank you for the hard work @tlamonthezie

**Review by ppebay — APPROVED** [review]
All local tests passing. Approved.

**Pull request merged**
