### PR TITLE
modify optimization loop to not be solely load-based

### LINKED ISSUE #123: Modify optimization loop to not be solely load-based
The current implementation below does not drive the optimization of communication weights:

Screen Shot 2021-12-09 at 1 43 10 PM

### PR DESCRIPTION
**Pull request by ppebay**
fixes #123

### CODE REVIEW

**Comment by ppebay** [comment]
Cf. discussion in #123

**Review by lifflander — APPROVED** [review]
Looks good!

**Comment by ppebay** [comment]
@marcinwrobel1986 can you please have a look at the CI error? Thanks

**Comment by marcinwrobel1986** [comment]
> @marcinwrobel1986 can you please have a look at the CI error? Thanks

@ppebay CI measures nothing, as I said last time on the meeting. Now CI is checking if theoretical value of imbalance is less than 0.04 I believe, which gives us nothing. Please create an issue and think about condition which should be satisfied in order for CI to pass, then I will set it up. I don't know maybe some ratio between calculated theoretical value and real value of imbalance...

**Comment by ppebay** [comment]
@marcinwrobel1986 alright but it was not failing before a few commits above.
Can you please check why it's failing and prevent it from returning an error so we can merge that PR? Thanks

**Pull request merged**
