### PR TITLE
#414 modify traversal of ranks to better emulate asynchrony

### LINKED ISSUE #375: Investigate why acceptance test at times fails
The `conf.yaml` test should always result in a 0-imbalance. The test parameters should be altered to ensure it always converges despite the probabilistic nature of the algorithm, while it currenly fails at times, e.g. in this [CI run](https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/4722515948/jobs/8382398068)

### LINKED ISSUE #414: Modify traversal of ranks to better emulate asynchrony
At a very least, albeit serial, rank traversal during LB should:
* be randomized;
* not always perform cluster swaps first (when relevant).

Please feel free to add other constraints @lifflander @nlslatt

### PR DESCRIPTION
**Pull request by ppebay**
Resolves #414 

Also improved the code as a result of the review of the control flow, by factoring out commonalities between the 2 transfer strategies and moving them to the abstract base strategy.

Resolves #375 as well, as discovered by @cwschilly

### CODE REVIEW

**Comment by ppebay** [comment]
Randomizing traversal order typical results in a different behavior of the LB iterations (below with the `Recursive` strategy) --- although we note than an optimal configuration is nonetheless attained:
Screen Shot 2023-08-03 at 12 51 25 AM
Screen Shot 2023-08-03 at 12 51 32 AM
Screen Shot 2023-08-03 at 12 51 40 AM

**Comment by ppebay** [comment]
In the case of the `Clustering` strategy, by adding another "layer" of randomization (in cluster selection as discussed @lifflander) we can indeed reproduce less-than-optimal results sometimes:
Screen Shot 2023-08-03 at 2 17 38 AM
Screen Shot 2023-08-03 at 2 18 04 AM

In contrast when `deterministic_transfer` is set to `True` we always find the known optimal value of 90.

**Comment by ppebay** [comment]
@cwschilly I am leaving the PR in this state, when you get a chance can you please look into the remaining CI failures? Thanks

**Comment by cwschilly** [comment]
@ppebay I just had to rebase on `develop` to get @tlamonthezie 's CI fix -- the PR now passes all tests

**Comment by cwschilly** [comment]
@lifflander @ppebay This PR is ready for review

**Review by lifflander — APPROVED** [review]
Looks good to me!

**Comment by ppebay** [comment]
Will let @cwschilly now test the CI as discussed with ordered sets for the `targets` when transfer phase is deterministic

**Comment by cwschilly** [comment]
@ppebay @lifflander I have run the acceptance test on this PR several times and analyzed the output, comparing with other runs that have failed. This PR consistently passes the test. I suspect it has to do with changing `deterministic_transfer` to `True` in `conf.yaml`. I believe this resolves #375

**Pull request merged**
