### PR TITLE
#266: 2D in-situ visualization capability

### LINKED ISSUE #266: ParaView scripting for post-hoc visualization
The goal of this issue is to add in-situ 2D visualization to LBAF, in order to give the user the option to entirely skip ParaView-based post-processing.

### PR DESCRIPTION
**Pull request by ppebay**
Fixes #266

### CODE REVIEW

**Comment by ppebay** [comment]
The in-situ VTK code will certainly need subsequent refactoring/modularization. However all key features are now present and a first pass of reviews would already be useful @nlslatt @lifflander @marcinwrobel1986

**Comment by ppebay** [comment]
I further ameliorated the rendering pipeline: it's now automatically computing parameters such as glyph radii and edge widths (amongst others) automatically, depending on mesh resolution; pixel rate; and grid properties.
output_file_00

big

I think this PR shall be ready for review/merge @nlslatt @lifflander @PhilMiller @marcinwrobel1986 when you get a chance. If improvements are sought (and this will happen) we can create subsequent issues therefore.

Thanks

**Comment by ppebay** [comment]
Some additional improvements
output_file_06

**Review by marcinwrobel1986 — APPROVED** [review]
Seems ok now and updated with develop

**Comment by ppebay** [comment]
Thanks @marcinwrobel1986 -- merging.

**Pull request merged**
