### PR TITLE
#317: Reformat style of lbsStatistics, remove special handling of text string for imbalance file

### LINKED ISSUE #317: Reformat style of lbsStatistics and remove special handling of text string for imbalance file output
* Doc strings are not consistent with code style
* This special case:  `if var_name == "final rank load" and file_name is not None` should be detected and treated outside of the statistics printout routine itself.

### PR DESCRIPTION
**Pull request by ppebay**
Fixes #317

### CODE REVIEW

**Comment by ppebay** [comment]
In passing @lifflander @nlslatt : is this `imbalance.txt` file (containing only the final value of the per-rank load imbalance) still needed? My recollection is that we wanted to use this for post-processing purposes, but the information is in the Exodus output anyway.

**Comment by ppebay** [comment]
Thanks @nlslatt , I guess we don't remember it, it probably means we don't need it -- if @lifflander agrees I will also remove it as part of this PR.

**Review by cz4rs — APPROVED** [review]
Looks good to me.
Regarding the style, long-term solution would be to use some linters ([we already do that with Python code in `build-stats` repo](https://github.com/DARMA-tasking/build-stats/blob/master/.github/workflows/run-linter.yml)).

**Comment by ppebay** [comment]
@cz4rs agreed -- in fact we had this somewhere in the "grand plan" for CI/CD but we never got to it I guess. Creating follow-on issue

**Pull request merged**
