### PR TITLE
60 rebase develop at commit 1427fc731e525c30ef69e06ba1df21bfa85192e3

### PR DESCRIPTION
**Pull request by marcinwrobel1986**
- soft reset to commit 1427fc731e525c30ef69e06ba1df21bfa85192e3

@lifflander I have noticed you added some new example data in:
`9befb21f Jonathan Lifflander <jliffla@sandia.gov> on 06.07.2020 at 00:13`
This was after 1427fc731e525c30ef69e06ba1df21bfa85192e3, so the question is should I put this data to this PR?

### CODE REVIEW

**Comment by ppebay** [comment]
@marcinwrobel1986 @lifflander 
If there is **sub**phase data then no it should not go into develop
The new rebased `develop` should not contain anything about subphase support

**Comment by lifflander** [comment]
I don't see any files changed yet. Is that correct?

**Comment by marcinwrobel1986** [comment]
I will take a look as well. Seems strange.

**Comment by marcinwrobel1986** [comment]
Ok, I needed to manually reverse changes.
@ppebay please take a look at log, I ran:
```
NodeGossiper.py -l ../../data/vt_example_lb_stats/stats -x 4 -y 2 -z 1 -s 0 -f 4 -k 4 -i 4 -c 1 -e
```
And I got following output:

Zrzut ekranu z 2021-02-01 20-07-50
Zrzut ekranu z 2021-02-01 20-08-07
Zrzut ekranu z 2021-02-01 20-08-27

I that is desired output, then it's ok.

**Comment by ppebay** [comment]
@marcinwrobel1986 Yes, it's looking good. With these parameters, the final load imbalance should always be brought down to less than 0.5. That could be something to be checked by the CI

**Comment by ppebay** [comment]
@marcinwrobel1986 I am talking of the LOAD imbalance. No link weights are considered in this example.

**Comment by marcinwrobel1986** [comment]
@lifflander as @ppebay has confirmed LBAF works as supposed. I think it could be merged, so develop works again.

**Review by ppebay — APPROVED** [review]

**Pull request merged**
