### PR TITLE
#457: Create 1.0.1 micro revision

### LINKED ISSUE #457: Create 1.0.1 micro revision
This is a follow-on to #440, which will integrate in particular  PR #454  (fixing #453 )

### PR DESCRIPTION
**Pull request by cwschilly**
Fixes #457

### CODE REVIEW

**Comment by cwschilly** [comment]
We should wait until PRs #460 , #459 , and #458 (this PR) are merged before creating the release.

**Review by ppebay — CHANGES_REQUESTED** [review]
Please @cwschilly integrate PR #451 once merged into `develop` before release. Then request new review. Thanks

**Comment by ppebay** [comment]
Sorry @cwschilly PR #451 was closed due to problems with it and replaced with PR #465 

Please wait for it to be merged before issuing 1.0.1

Sorry for hassle

**Comment by cwschilly** [comment]
Hello @ppebay now that #459, #460, and #465 have been merged, we are ready to release v1.0.1

**Review by ppebay — APPROVED** [review]
Good for me

**Pull request merged**
