### PR TITLE
#370: make categorical labels integers

### LINKED ISSUE #370: Make categorical labels integer when numeric
In cases where the QOI is categorical, make categories integers (i.e., not print the decimal part) so that they fit better

As suggested by @nlslatt

### PR DESCRIPTION
**Pull request by cwschilly**
Fixes #370

### CODE REVIEW

**Comment by cwschilly** [comment]
This fix appears to work, but I'm not sure how to test with data that would yield decimal labels. @nlslatt , if you have a sample config file that produced the problem in #370 , please include it here so that I can test out this solution.

**Comment by ppebay** [comment]
Any update @cwschilly on testing this PR?

**Comment by cwschilly** [comment]
@ppebay No update yet; if there is a sample config file that produces the error, that would be great to be able to test on

**Comment by ppebay** [comment]
Thanks @cwschilly I added @nlslatt as reviewer

**Comment by cwschilly** [comment]
This will print labels like "1.0" and "2.0" as "1" and "2", but any other decimals (like "1.5") are still printed as such.

**Review by ppebay — APPROVED** [review]
Perfect

**Pull request merged**
